openapi: 3.0.4
info:
  title: Aembit Edge API
  version: v1
servers:
  - url: https://{tenant}.aembit.io
    variables:
      tenant:
        default: tenant
        description: Aembit Tenant ID
paths:
  /edge/v1/auth:
    post:
      tags:
        - Auth
      summary: Authenticate to the Edge API
      description: Authenticates Client Workloads to Aembit Edge using a Trust Provider
      operationId: edge-api-auth
      parameters:
        - name: X-Aembit-ResourceSet
          in: header
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthRequest"
      responses:
        "200":
          description: Successfully retrieved access token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenDTO"
        "400":
          description: Invalid request or missing parameters
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponseDTO"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponseDTO"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponseDTO"
  /edge/v1/credentials:
    post:
      tags:
        - Credentials
      summary: Get credentials for a Client Workload
      description: Retrieves credentials for a Client Workload based on your
        configured Access Policies
      operationId: edge-api-get-credentials
      parameters:
        - name: X-Aembit-ResourceSet
          in: header
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ApiCredentialsRequest"
      responses:
        "200":
          description: Credentials returned for specified Client Workload
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiCredentialsResponse"
        "400":
          description: Invalid request or missing parameters
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericResponseDTO"
components:
  schemas:
    ApiCredentialsRequest:
      title: CredentialsRequest
      type: object
      properties:
        client:
          $ref: "#/components/schemas/ClientWorkloadDetails"
        server:
          $ref: "#/components/schemas/ServerWorkloadDetails"
        credentialType:
          $ref: "#/components/schemas/CredentialProviderTypes"
      additionalProperties: false
      description: Request payload for retrieving credentials for a Client Workload
    ApiCredentialsResponse:
      title: CredentialsResponse
      type: object
      properties:
        credentialType:
          $ref: "#/components/schemas/CredentialProviderTypes"
        expiresAt:
          type: string
          description: Token expiration time in ISO 8601 format, null for non-expiring
            credentials
          format: date-time
          nullable: true
        data:
          $ref: "#/components/schemas/EdgeCredentials"
      additionalProperties: false
      description: Response containing credentials that a Client Workload requests
        with expiration details
    AuthRequest:
      title: AuthRequest
      type: object
      properties:
        clientId:
          type: string
          description: Trust Provider Client Id for authentication
          nullable: true
        client:
          $ref: "#/components/schemas/ClientWorkloadDetails"
      additionalProperties: false
      description: Identity and attestation information for Client Workload authentication
    AwsDTO:
      type: object
      properties:
        instanceIdentityDocument:
          type: string
          description: Base64-encoded AWS instance identity document
          nullable: true
        instanceIdentityDocumentSignature:
          type: string
          description: Base64-encoded signature for AWS instance identity document
            verification
          nullable: true
        lambda:
          $ref: "#/components/schemas/LambdaDTO"
        ecs:
          $ref: "#/components/schemas/AwsEcsDTO"
        stsGetCallerIdentity:
          $ref: "#/components/schemas/StsGetCallerIdentityDTO"
      additionalProperties: false
      description: AWS-specific attestation data for Client Workload identification
    AwsEcsDTO:
      type: object
      properties:
        containerMetadata:
          type: string
          description: JSON string containing AWS ECS container metadata
          nullable: true
        taskMetadata:
          type: string
          description: JSON string containing AWS ECS task metadata
          nullable: true
      additionalProperties: false
      description: AWS ECS container and task metadata for workload attestation
    AzureAttestationDTO:
      type: object
      properties:
        attestedDocument:
          $ref: "#/components/schemas/AzureAttestedDocumentDTO"
      additionalProperties: false
      description: Azure-specific attestation data for Client Workload identification
    AzureAttestedDocumentDTO:
      type: object
      properties:
        encoding:
          type: string
          description: Encoding format of the Azure attestation document
          nullable: true
        signature:
          type: string
          description: Digital signature for Azure attestation document verification
          nullable: true
        nonce:
          type: string
          description: Cryptographic nonce for Azure attestation document freshness
          nullable: true
      additionalProperties: false
      description: Azure attested document with signature and nonce for verification
    ClientWorkloadDetails:
      type: object
      properties:
        sourceIP:
          type: string
          description: IP address of the requesting Client Workload
          nullable: true
        aws:
          $ref: "#/components/schemas/AwsDTO"
        azure:
          $ref: "#/components/schemas/AzureAttestationDTO"
        gcp:
          $ref: "#/components/schemas/GcpAttestationDTO"
        os:
          $ref: "#/components/schemas/OsDTO"
        k8s:
          $ref: "#/components/schemas/K8sDTO"
        host:
          $ref: "#/components/schemas/HostDTO"
        github:
          $ref: "#/components/schemas/IdentityTokenAttestationDTO"
        terraform:
          $ref: "#/components/schemas/IdentityTokenAttestationDTO"
        gitlab:
          $ref: "#/components/schemas/IdentityTokenAttestationDTO"
        oidc:
          $ref: "#/components/schemas/IdentityTokenAttestationDTO"
      additionalProperties: false
      description: Identity and attestation information for a Client Workload
        requesting credentials
    CredentialProviderTypes:
      enum:
        - Unknown
        - ApiKey
        - UsernamePassword
        - GoogleWorkloadIdentityFederation
        - OAuthToken
        - AwsStsFederation
      type: string
      description: Type of credential being requested from your configured Credential
        Provider
    CrowdStrikeDTO:
      type: object
      properties:
        agentId:
          type: string
          description: Unique identifier for the CrowdStrike agent
          nullable: true
      additionalProperties: false
      description: CrowdStrike agent information for endpoint security attestation
    EdgeCredentials:
      type: object
      properties:
        apiKey:
          type: string
          description: API key credential for authenticating to target services
          nullable: true
        token:
          type: string
          description: Bearer token credential for authenticating to target services
          nullable: true
        username:
          type: string
          description: Username for basic authentication credentials
          nullable: true
        password:
          type: string
          description: Password for basic authentication credentials
          nullable: true
        awsAccessKeyId:
          type: string
          description: AWS access key ID for programmatic access
          nullable: true
        awsSecretAccessKey:
          type: string
          description: AWS secret access key for programmatic access
          nullable: true
        awsSessionToken:
          type: string
          description: AWS session token for temporary credentials
          nullable: true
      additionalProperties: false
      description: Credential data returned to Client Workloads based on your
        configured Credential Providers
    EnvironmentDTO:
      type: object
      properties:
        K8S_POD_NAME:
          type: string
          description: Kubernetes pod name environment variable
          nullable: true
        CLIENT_WORKLOAD_ID:
          type: string
          description: Aembit Client Workload identifier environment variable
          nullable: true
        KUBERNETES_PROVIDER_ID:
          type: string
          description: Kubernetes Trust Provider identifier environment variable
          nullable: true
        AEMBIT_RESOURCE_SET_ID:
          type: string
          description: Aembit Resource Set identifier environment variable
          nullable: true
      additionalProperties: false
      description: Environment variables available to the Client Workload
    GcpAttestationDTO:
      type: object
      properties:
        identityToken:
          type: string
          description: Identity token for workload attestation
          nullable: true
        instanceDocument:
          type: string
          description: Base64-encoded GCP instance identity document
          nullable: true
      additionalProperties: false
      description: GCP-specific attestation data for Client Workload identification
    GenericResponseDTO:
      type: object
      properties:
        success:
          type: boolean
          description: True if the API call was successful, False otherwise
        message:
          type: string
          description: Message to indicate why the API call failed
          nullable: true
        id:
          type: integer
          description: Unique identifier of the API response
          format: int32
      additionalProperties: false
      description: DTO for a Generic API Response
    HostDTO:
      type: object
      properties:
        hostname:
          type: string
          description: Client Workload hostname
          nullable: true
        domainName:
          type: string
          description: Domain name of the Client Workload host
          nullable: true
        process:
          $ref: "#/components/schemas/ProcessDTO"
        sensors:
          $ref: "#/components/schemas/SensorsDTO"
        systemSerialNumber:
          type: string
          description: Hardware serial number of the Client Workload system
          nullable: true
        networkInterfaces:
          type: array
          items:
            $ref: "#/components/schemas/NetworkInterfacesDTO"
          nullable: true
      additionalProperties: false
      description: Host system information for Client Workload attestation
    IdentityTokenAttestationDTO:
      type: object
      properties:
        identityToken:
          type: string
          description: Identity token for workload attestation
          nullable: true
      additionalProperties: false
      description: JWT-based identity token attestation for CI/CD platforms
    K8sDTO:
      type: object
      properties:
        serviceAccountToken:
          type: string
          description: Kubernetes service account JWT token
          nullable: true
      additionalProperties: false
      description: Kubernetes-specific attestation data for Kubernetes pod identification
    LambdaDTO:
      type: object
      properties:
        arn:
          type: string
          description: AWS Lambda function ARN
          nullable: true
      additionalProperties: false
      description: AWS Lambda function information for serverless workload attestation
    NetworkInterfacesDTO:
      type: object
      properties:
        name:
          type: string
          nullable: true
        macAddress:
          type: string
          nullable: true
        ipv4Addresses:
          type: array
          items:
            type: string
          nullable: true
        ipv6Addresses:
          type: array
          items:
            type: string
          nullable: true
      additionalProperties: false
    OsDTO:
      type: object
      properties:
        environment:
          $ref: "#/components/schemas/EnvironmentDTO"
      additionalProperties: false
      description: Operating system environment information for Client Workload attestation
    ProcessDTO:
      type: object
      properties:
        name:
          type: string
          description: Process name
          nullable: true
        pid:
          type: integer
          description: Process identifier (PID)
          format: int32
        userId:
          type: integer
          description: User identifier running the process
          format: int32
        userName:
          type: string
          description: Username running the process
          nullable: true
        exePath:
          type: string
          description: Executable file path of the process
          nullable: true
      additionalProperties: false
      description: Process information for Client Workload identification
    SensorsDTO:
      type: object
      properties:
        crowdStrike:
          $ref: "#/components/schemas/CrowdStrikeDTO"
      additionalProperties: false
      description: Security sensor data for enhanced Client Workload attestation
    ServerWorkloadDetails:
      type: object
      properties:
        transportProtocol:
          $ref: "#/components/schemas/TransportProtocol"
        host:
          type: string
          description: Target server hostname or IP address
          nullable: true
        port:
          type: integer
          description: Target server port number
          format: int32
      additionalProperties: false
      description: Target server connection details for credential requests
    StsGetCallerIdentityDTO:
      type: object
      properties:
        headers:
          type: object
          additionalProperties:
            type: string
            nullable: true
          description: HTTP headers for AWS STS GetCallerIdentity request
          nullable: true
        region:
          type: string
          description: AWS region for STS GetCallerIdentity request
          nullable: true
      additionalProperties: false
      description: AWS STS GetCallerIdentity request data for identity verification
    TokenDTO:
      type: object
      properties:
        accessToken:
          type: string
          description: Bearer token for authenticating subsequent API requests
          nullable: true
        tokenType:
          type: string
          description: Token type, typically 'Bearer' for OAuth2-style tokens
          nullable: true
        expiresIn:
          type: integer
          description: Token expiration time in seconds from issuance
          format: int32
      additionalProperties: false
      description: OAuth2-style access token response with expiration details
    TransportProtocol:
      enum:
        - TCP
      type: string
  securitySchemes:
    bearerAuth:
      type: http
      description: Bearer token authentication using Aembit Edge API access tokens
        obtained via the /edge/v1/auth endpoint
      scheme: bearer
      bearerFormat: Reference
security:
  - bearerAuth:
      - read
